### ISSUE TITLE
Please add the connector version in the header of the release

### ISSUE THREAD

**Issue by si-heger** [NetAppDocs/bluexp-relnotes#60]
### Page URL

https://docs.netapp.com/us-en/bluexp-relnotes/whats-new.html

### Page title

Recent changes in BlueXP

### Summary

This is by customer request: It would be great if we could add the connector version in the header of the release section. E. g. for "7 October 2024" we could add in the same line or in the line below the version number. In this example it would be 3.9.45. This helps customers and internal folks to identify quicker to which Connector release the news are related.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@si-heger, thanks for reaching out. I sent you an email for additional clarification.

**Comment by netapp-bcammett** [comment]
Due to our standards and automation that we have in place, I can't place a version number directly in the release date header.

For many releases (other than the 7 October release), the Connector version is listed immediately under the release date. 

Going forward, we'll be more consistent with listing the Connector release first so that it's easier to make that connection.

Thanks again,
Ben
